INSERT INTO etiquetas (id,nombre) VALUES (1,'Robótica');
INSERT INTO etiquetas (id,nombre) VALUES (2,'Computación');
INSERT INTO etiquetas (id,nombre) VALUES (3,'Teléfonos Móviles');
INSERT INTO etiquetas (id,nombre) VALUES (4,'Automovilismo');
INSERT INTO etiquetas (id,nombre) VALUES (5,'Campeonatos');
INSERT INTO etiquetas (id,nombre) VALUES (6,'Equipos');
INSERT INTO etiquetas (id,nombre) VALUES (7,'Bolsa de valores');
INSERT INTO etiquetas (id,nombre) VALUES (8,'Inversiones');
INSERT INTO etiquetas (id,nombre) VALUES (9,'Brokers');
INSERT INTO etiquetas (id,nombre) VALUES (10,'Celebridades');
INSERT INTO etiquetas (id,nombre) VALUES (11,'Eventos');
INSERT INTO etiquetas (id,nombre) VALUES (12,'Moda');
INSERT INTO etiquetas (id,nombre) VALUES (13,'Avances');
INSERT INTO etiquetas (id,nombre) VALUES (14,'Nobel');
INSERT INTO etiquetas (id,nombre) VALUES (15,'Matemáticas');
INSERT INTO etiquetas (id,nombre) VALUES (16,'Química');
INSERT INTO etiquetas (id,nombre) VALUES (17,'Física');
INSERT INTO etiquetas (id,nombre) VALUES (18,'Largo plazo');
INSERT INTO etiquetas (id,nombre) VALUES (19,'Bienes Raíces');
INSERT INTO etiquetas (id,nombre) VALUES (20,'Estilo');